# Generated by Django 2.2.7 on 2020-11-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_create_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('emergency', models.PositiveIntegerField(blank=True, null=True)),
                ('prime', models.PositiveIntegerField(blank=True, null=True)),
                ('transportation_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('enter_diagnosis', models.TextField(blank=True, null=True)),
                ('diagnoses_divergence', models.TextField(blank=True, null=True)),
                ('in_date', models.DateTimeField(blank=True, null=True)),
                ('work_capacity_name', models.CharField(blank=True, max_length=100, null=True)),
                ('clinical_course', models.TextField(blank=True, null=True)),
                ('out_date', models.DateTimeField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('m_record_mkb_name', models.TextField(blank=True, null=True)),
                ('visit_result_name', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='api.Person')),
            ],
        ),
    ]
