# Generated by Django 2.2.7 on 2020-11-21 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensaryRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp_health_group_value', models.CharField(blank=True, max_length=100, null=True)),
                ('d_registration_mkb_name', models.TextField(blank=True, null=True)),
                ('diagnosis_note', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('change_date', models.DateField(blank=True, null=True)),
                ('disp_remove_reason_name', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_registrations', to='api.Person')),
            ],
        ),
    ]
