# Generated by Django 2.2.7 on 2020-11-21 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dispensaryregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnesis_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('anamnesis_date', models.DateField(blank=True, null=True)),
                ('anamnesis', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis', to='api.Person')),
            ],
        ),
    ]
