# Generated by Django 2.2.7 on 2020-11-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_anamnesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='blood_sugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='body_mass_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='cholesterol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
