# Generated by Django 2.2.7 on 2020-11-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_fields_to_medical_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='heart_disease_risk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
