# Generated by Django 2.2.7 on 2020-11-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_fields_age_gender_to_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='diastolic_blood_pressure',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='systolic_blood_pressure',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
