# Generated by Django 2.2.7 on 2020-12-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=4, null=True)),
                ('heart_disease_risk', models.BooleanField(blank=True, default=False, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
