# Generated by Django 2.2.7 on 2020-12-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_create_person_for_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(blank=True, max_length=100, null=True)),
                ('service_name', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_paraclinic', models.CharField(blank=True, max_length=100, null=True)),
                ('is_operation', models.CharField(blank=True, max_length=100, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('specialist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('property_id', models.CharField(blank=True, max_length=100, null=True)),
                ('property_name', models.CharField(blank=True, max_length=255, null=True)),
                ('property_value', models.CharField(blank=True, max_length=255, null=True)),
                ('measurename', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_tests', to='training.Person')),
            ],
        ),
    ]
